[package]
name = "slpdexdb_db"
version = "0.1.0"
authors = ["tobiasruck <ruck.tobias@gmail.com>"]
edition = "2018"

#[lib]
#name = "slpdex_backend"
#crate-type = ["cdylib"]

[dependencies]
cashcontracts = { git = "https://github.com/slpdex/cashcontracts-rs" }
slpdexdb_base = {"path"="../slpdexdb_base"}
panda-base = { package = "cryptopandas_base", path = "../cryptopandas_base" }
byteorder = "1.3.2"
hex = "0.3.2"
#hex-literal = "0.2.0"
base64 = "0.10.1"
#rand = "0.7.0"
diesel = { version = "1.4.2", features = ["postgres", "chrono", "r2d2"] }
chrono = "0.4.7"
reqwest = "0.9.19"
serde = { version = "1.0.97", features = ["derive"] }
serde_json = "1.0.40"
json = "0.11.14"
num = "0.2.0"
num-traits = "0.2"
num-derive = "0.2"
secp256k1 = "0.15.5"
#error-chain = "0.12.1"

[dependencies.rug]
version = "1.5.1"
default-features = false
features = ["integer", "rational"]

#[dependencies.pyo3]
#version = "0.7.0"
#features = ["extension-module"]
